// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0MGWCTpegqbuDURPiChJlf7LHp2DqK-E',
    authDomain: 'vetement-894d3.firebaseapp.com',
    projectId: 'vetement-894d3',
    storageBucket: 'vetement-894d3.firebasestorage.app',
    messagingSenderId: '280522494965',
    appId: '1:280522494965:web:22635eecf1c2cc002ec6bc',
    measurementId: 'G-FLGWHFCBJB',
    databaseURL: 'https://vetement-894d3-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7KDbMVRV0H15A3b3aKlnNZtcRDfLcU1A',
    appId: '1:280522494965:android:1ce52a67ddba80ba2ec6bc',
    messagingSenderId: '280522494965',
    projectId: 'vetement-894d3',
    storageBucket: 'vetement-894d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm-RcAvAnxUip8hOCVmoQFTvO86BcBsak',
    appId: '1:280522494965:ios:557aacc152033e222ec6bc',
    messagingSenderId: '280522494965',
    projectId: 'vetement-894d3',
    storageBucket: 'vetement-894d3.firebasestorage.app',
    iosBundleId: 'com.saad',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-HqnhA5gMS4hZN_Kj-pKLU27NLR1zTo',
    appId: '1:124193868831:ios:52261dd31dfe16fa88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    storageBucket: 'vetementia.firebasestorage.app',
    iosBundleId: 'com.saad.vetementIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFMLDrHe2MiSC9UpyTZcGsej1_BqLLneo',
    appId: '1:124193868831:web:e75ca400086e1a7b88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    authDomain: 'vetementia.firebaseapp.com',
    storageBucket: 'vetementia.firebasestorage.app',
  );
}
